asset_path: exts/cat_envs/cat_envs/assets/Robots/odri/AlienGo_description/aliengo.urdf
usd_dir: aliengo_usd
usd_file_name: aliengo_description.usd
force_usd_conversion: true
make_instanceable: true
import_inertia_tensor: true
fix_base: false
merge_fixed_joints: false
self_collision: true
default_drive_type: none
override_joint_dynamics: false
default_drive_stiffness: 0.0
default_drive_damping: 0.0
link_density: 0.0
convex_decompose_mesh: false


